add count.index to role
Solves the following error:
Error: Missing resource instance key
│ 
│   on .terraform/modules/cloudsploit/iam_cloudsploit_role.tf line 32, in resource "aws_iam_role_policy_attachment" "cloudsploit_cross_account_attach":
│   32:   role       = "${aws_iam_role.cloudsploit_cross_account_role.name}"
│ 
│ Because aws_iam_role.cloudsploit_cross_account_role has "count" set, its attributes must be accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     aws_iam_role.cloudsploit_cross_account_role[count.index]